Loopring/protocols

- docs/index.html
- packages/oedax_v1/contracts/iface/IAuction.sol
- packages/oedax_v1/contracts/iface/IAuctionData.sol
- packages/oedax_v1/contracts/iface/ICurve.sol
- packages/oedax_v1/contracts/iface/IOedax.sol
- packages/oedax_v1/contracts/impl/Auction.sol
- packages/oedax_v1/contracts/impl/Curve.sol
- packages/oedax_v1/contracts/impl/Oedax.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionAsks.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionBids.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionSettlement.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionStatus.sol
Reverts Loopring/protocols#175
> Revert "[Oedax] greatly simplify bounding curves"

- packages/oedax_v1/contracts/iface/IAuction.sol
- packages/oedax_v1/contracts/iface/IAuctionData.sol
- packages/oedax_v1/contracts/iface/IOedax.sol
- packages/oedax_v1/contracts/impl/Auction.sol
- packages/oedax_v1/contracts/impl/Oedax.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionAsks.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionBids.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionSettlement.sol
Probably still contains some issues.
Not sure yet how to best reward the withdrawer so this is not yet implemented.
Maybe we can even fine the owner for not withdrawing for it's users if he can set some kind of withdrawing fee some way.
> [Oedax] Settlement refactor

- packages/oedax_v1/contracts/iface/IAuction.sol
- packages/oedax_v1/contracts/iface/IAuctionData.sol
- packages/oedax_v1/contracts/iface/IOedax.sol
- packages/oedax_v1/contracts/impl/Auction.sol
- packages/oedax_v1/contracts/impl/Oedax.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionAsks.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionBids.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionSettlement.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionStatus.sol
- packages/oedax_v1/test/testOedax.js
@dong77 I removed `settlementTime`, which may or may not be correct because it changes the logic in `getAuctionStatus` slightly. Though I think once the auction has closed it will remain closed so we shouldn't need it there.
> [Oedax] Settlement unification

- packages/oedax_v1/contracts/impl/Oedax.sol
- packages/oedax_v1/contracts/impl/libauction/AuctionSettlement.sol
- packages/oedax_v1/test/testAuction.js
拍卖失败时，不应该再计算token相关的费用，token都已经返回给用户，这是即便有和token相关的费用，拍卖合约上也已经没有token余额可以操作了。
> [Oedax] fix bugs while settling

- packages/loopring_v3/generate_keys.py
- packages/loopring_v3/operator/generate_keys.py
A small tool for generating vk, pk files for circuits
Now works with blockType of deposit and onchainWithdrawal, 
still has some issues with offchainWithdrawal and trade keys generating.
> add a tool for generating circuit keys

- packages/loopring_v3/contracts/iface/IProtocolFeeManager.sol
- packages/loopring_v3/contracts/iface/IUserStakingPool.sol
- packages/loopring_v3/contracts/impl/ProtocolFeeManager.sol
- packages/loopring_v3/package.json
- packages/oedax_v1/contracts/iface/IOedax.sol
- packages/oedax_v1/contracts/impl/Auction.sol
- packages/oedax_v1/contracts/impl/Oedax.sol
- packages/oedax_v1/migrations/5_create_auctions.js
- packages/oedax_v1/package.json
Also remove the 'ranking' concept from Oedax
> [Protocol3] Implement auction using Oedax

- packages/loopring_v3/contracts/impl/LOOP.sol
- packages/loopring_v3/contracts/lib/MintableERC20.sol
- packages/loopring_v3/contracts/lib/MintableNonTransferableERC20Token.sol
Add MintableNonTransferableERC20Token for future Loopring DAO reputation token
> [Protocol3] Add MintableNonTransferableERC20Token and LOOP token

- packages/loopring_v2/contracts/helper/OrderHelper.sol
> [Protocol2] Enable the use of order.transferDataS

- packages/loopring_v3/contracts/iface/IProtocolFeeManager.sol
This will be in sync with our medium post: https://medium.com/p/d7da9ac79d3d/edit
> [Loopring3] 20% to DAO and 10% burned

- packages/loopring_v3/contracts/impl/libexchange/ExchangeWithdrawals.sol
> [Protocol3] Add safety check for invalid accountID for token transfers

- packages/loopring_v2/contracts/helper/OrderHelper.sol
- packages/loopring_v2/contracts/helper/ParticipationHelper.sol
- packages/loopring_v2/contracts/helper/RingHelper.sol
- packages/loopring_v2/contracts/iface/IRingSubmitter.sol
- packages/loopring_v2/contracts/impl/BurnRateTable.sol
Makes necessary changes to further fix order matching to conform to Dolomite's expectations
> [Protocol2] Changes necessary for Dolomite's launch & re-deployment 

- packages/oedax_v1/package.json
> oedax_v1 update lodash 4.17.14

- packages/loopring_v2/package.json
> loopring_v2 update lodash 4.17.14

- packages/loopring_v1/package.json
> loopring_v1 update lodash 4.17.14

- packages/loopring_v3/package.json
>  loopring_v3 update lodash 4.17.14

- packages/loopring_v3/docker/build_image.sh
> [Protocol3] Fix Docker script compile error (#344)

- packages/loopring_v3/docker/.gitignore
> [Protocol3] Add contracts dump file to gitignore (#346)

- packages/loopring_v3/contracts/impl/LoopringV3.sol
> [Protocol3] Fix a bug?

- packages/loopring_v3/contracts/iface/IExchange.sol
- packages/loopring_v3/contracts/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/iface/ILoopring.sol
- packages/loopring_v3/contracts/iface/IProtocolRegistry.sol
- packages/loopring_v3/contracts/impl/ExchangeProxy.sol
- packages/loopring_v3/contracts/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/impl/LoopringV3.sol
- packages/loopring_v3/contracts/impl/ProtocolRegistry.sol
- packages/loopring_v3/contracts/thirdparty/Clonable.sol
- packages/loopring_v3/migrations/4_deploy_registry.js
- packages/loopring_v3/migrations/5_deploy_auxiliaries.js
- packages/loopring_v3/migrations/6_deploy_exchange.js
- packages/loopring_v3/migrations/7_deploy_protocol.js
- packages/loopring_v3/package.json
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/util/Artifacts.ts
ILoopringV3 no longer creates IExchangeV3 instances.
> [Protocol3] Decouple exchange contract and loopring contract

- packages/loopring_v3/contracts/iface/IAddressWhitelist.sol
- packages/loopring_v3/contracts/iface/IBlockVerifier.sol
- packages/loopring_v3/contracts/iface/IExchange.sol
- packages/loopring_v3/contracts/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/iface/IImplementationManager.sol
- packages/loopring_v3/contracts/iface/ILoopring.sol
- packages/loopring_v3/contracts/iface/ILoopringV3.sol
- packages/loopring_v3/contracts/iface/IProtocolFeeVault.sol
- packages/loopring_v3/contracts/iface/IUniversalRegistry.sol
- packages/loopring_v3/contracts/iface/IUserStakingPool.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
> [Protocols] fix some minor documentation issue

- packages/lightcone_v2.js/Dockerfile
- packages/lightcone_v2.js/package-lock.json
- packages/lightcone_v2.js/package.json
This will simplify the build process and how to import it in tokenbank-web
> [Lightcone_v2.js] Remove gRPC in lightcone_v2.js as it's not needed

- packages/loopring_v3/contracts/impl/UserStakingPool.sol
Recommit https://github.com/Loopring/protocols/pull/496
to fix build issue
> [protocol3] Type convert uint to uint64 to reduce gas cost

- packages/loopring_v3/test/testExchangeBlocks.ts
This reverts commit 137e598900b84fa78f94798c2ba021881c369791.
> Revert "[Protocol3] Add missed const cases (#621)"

- packages/loopring_v3/contracts/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeAdmins.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeConstants.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
- packages/loopring_v3/test/testExchangeBlocks.ts
- packages/loopring_v3/test/testExchangeShutdown.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testOperator.ts
This is to address issue https://github.com/Loopring/protocols/issues/603
The reasons we propose to relax those constants:
- Our backend is not fully ready to handle all situations.
- We need to cope with the scenario where all off-chain data are completely lost and not recoverable
- We need to cope with the scenario where the Ethereum network is overused and transactions are pending for days.
https://docs.google.com/spreadsheets/d/1XKOKUtLdh7PZgKWs5HRxK_wrCyt4FbHhRdL4SAW7_Cw/edit#gid=1428741813
> [Protocol3] update protocol constant values

- packages/loopring_v3/contracts/impl/LRCBalanceBasedAddressWhitelist.sol
- packages/loopring_v3/package-lock.json
`LRCBalanceBasedAddressWhitelist` will treat an address as whitelisted if its LRC balance plus its outstanding LRC balance in the Long-Term-Incentive-Plan is greater than a threshold.
> [Protocol3] add LRCBalanceBasedAddressWhitelist

- packages/tokenbank_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/tokenbank_v1/contracts/price/AggregationalPriceOracle.sol
- packages/tokenbank_v1/contracts/price/KyberNetworkPriceOracle.sol
- packages/tokenbank_v1/contracts/price/UniswapPriceOracle.sol
Implement Uniswap and KyberNetwork price oracle.
> [tokenbank] Price provider implementation

- packages/hebao_v1/contracts/base/BaseVault.sol
- packages/hebao_v1/contracts/base/ERC1271Module.sol
- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/iface/Vault.sol
- packages/hebao_v1/contracts/lib/SignatureUtil.sol
- packages/hebao_v1/contracts/modules/dapps/CompoundModule.sol
- packages/hebao_v1/contracts/modules/dapps/DyDxModule.sol
- packages/hebao_v1/contracts/modules/dapps/MakerModule.sol
- packages/hebao_v1/contracts/modules/dapps/PoolTogetherModule.sol
- packages/hebao_v1/contracts/modules/dapps/UniswapModule.sol
- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/LockModule.sol
- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/modules/security/RecoveryModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/ApprovedTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/docs/DESIGN.md
Try to solve issue https://github.com/Loopring/protocols/issues/780
> [hebao] support multiple types of signatures.

- packages/hebao_v1/contracts/base/MetaTxModule.sol
To address https://github.com/Loopring/protocols/issues/787
> [hebao] force nonce increase by 1

- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
Fixing https://github.com/Loopring/protocols/issues/753
> [hebao] fix issue in calling Loopring getAccount method

- packages/hebao_v1/contracts/base/BaseModule.sol
- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/iface/Wallet.sol
- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
addressing https://github.com/Loopring/protocols/issues/785
> [hebao] support delegatecall in wallet transact

- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/stores/WhitelistStore.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
addressing  issue https://github.com/Loopring/protocols/issues/775
> [hebao] Delayed whitelisting

- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
- packages/hebao_v1/contracts/modules/security/LockModule.sol
- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
addressing  https://github.com/Loopring/protocols/issues/786
> [hebao] add gasOverhead parameter to executeMetaTx

- packages/hebao_v1/contracts/base/MetaTxModule.sol
After seeing #800 it dawned on me that sending `msg.value` to the module functions doesn't make that much sense sense because it's the wallet address that needs to pay the ETH. This PR deposits all `msg.value` requested to the wallet immediately.
> [hebao] Send msg.value of a meta-tx directly to the wallet

- packages/hebao_v1/contracts/base/ControllerImpl.sol
- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/iface/Controller.sol
- packages/hebao_v1/contracts/iface/QuotaManager.sol
- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
A possible improvement to this PR is to have two quotas per wallet, one for transfers, and one for gas.
> [hebao] trace meta-tx gas

- packages/hebao_v1/contracts/base/MetaTxModule.sol
Currently the gas costs charged to the user can be higher than `gasUsed + gasOverhead` which is not something you'd expect or want.
This PR changes the gas cost calculation slightly to make sure the actual call the user wants to do can use up to `gasLimit` gas. Any other costs need to be included in `gasOverhead`. The total cost charged to the user is at most `gasLimit + gasOverhead`, as expected and signed by the user.
> [hebao] Enforce user defined maximum gas cost

- packages/hebao_v1/contracts/base/ControllerImpl.sol
- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/iface/Controller.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
Modules are not supposed to hold any assets.
> [hebao] add a collectTokens to MetaTxModule

- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
Now the wallet owner can only wait on the pending tx to expire. Doesn't hurt to being able to cancel a pending tx immediately (like in cases the owner afterwards used `ApprovedTransfers` because it ended up being quicker).
> [hebao] Allow cancelling pending transactions

- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
If the wallet owner can add to the whitelist with a delay, than I think we can allow adding to the whitelist immediately with a majority (with wallet owner signature required). This can be useful for when the owner has another secure address (or even an exchange address) without having to wait on the delay. If an attacker has a majority he is already able to use `ApprovedTransfers` without any limits, so this doesn't decrease the security.
> [hebao] Allow adding to the whitelist immediately with majority

- packages/loopring_v3/contracts/iface/IDelayedTransaction.sol
- packages/loopring_v3/contracts/impl/owners/DelayedOwner.sol
- packages/loopring_v3/contracts/lib/DelayedTransaction.sol
- packages/loopring_v3/contracts/test/DelayedOwnerContract.sol
- packages/loopring_v3/test/testDelayedOwner.ts
Some small changes I did for testing chainlink.
> [protocol3] Some small improvements to DelayedOwner

- packages/loopring_v3/deployment_mainnet.md
WEDAX -> WEDEX
depoyer -> deployer
> few small typos

- packages/loopring_v3/contracts/iface/ILoopringV3.sol
- packages/loopring_v3/contracts/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/impl/LoopringV3.sol
- packages/loopring_v3/contracts/impl/UniversalRegistry.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeAdmins.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeTokens.sol
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeMaintenanceMode.ts
- packages/loopring_v3/test/testExchangeTokens.ts
- packages/loopring_v3/test/testExchangeUtil.ts
This PR is to address issue https://github.com/Loopring/protocols/issues/903
>  Burn to vault

- packages/loopring_v3/deployment_mainnet_v3.1.1.md
> [LoopringV3] update ProtocolFeeVault and UniswapTokenSeller addresses

- packages/hebao_v1/contracts/stores/WhitelistStore.sol
> [hebao_v1] add timestamp in Whitelisted event

- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/test/testGuardians.ts
> [HEBAO_v1] fix issue #1086

- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
Use newer try catch syntax to detect failures.
> [hebao] Use try/catch in getDEXAccount

- packages/hebao_v1/contracts/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactoryModule.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/testEns.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
- packages/hebao_v1/test/testRecovery.ts
- packages/hebao_v1/test/testWalletCreation.ts
> [hebao] Fixed wallet creation/contract call issues

- packages/hebao_v1/contracts/iface/Data.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
- packages/hebao_v1/migrations/8_modules.js
- packages/hebao_v1/test/helpers/GuardianUtils.ts
- packages/hebao_v1/test/testGuardians.ts
- packages/hebao_v1/test/testMajority.ts
Fix issue #1099 
All tests passed.
> [HEBAO-V1] enable auto comfirmation for guardian addition and removal

- packages/loopring_v3.js/src/babyjub.js
- packages/loopring_v3.js/src/eddsa.ts
- packages/loopring_v3.js/src/poseidon.js
- packages/loopring_v3/Makefile
- packages/loopring_v3/package.json
snarkjs was updated in #1109 but the update contains breaking changes.
> [protocol3] Updates for snarkjs 0.1.31

- packages/hebao_v1/contracts/lib/OwnerManagable.sol
- packages/hebao_v1/contracts/modules/core/WalletFactoryModule.sol
- packages/hebao_v1/contracts/test/lib/SignatureUtilWrapper.sol
- packages/hebao_v1/contracts/thirdparty/ens/BaseENSManager.sol
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/lib/testSignatureUtil.ts
- packages/hebao_v1/test/testEns.ts
- packages/hebao_v1/test/testRecovery.ts
- packages/hebao_v1/test/testWalletCreation.ts
> improve kongliang's implementation

- packages/hebao_v1/contracts/iface/Module.sol
- packages/hebao_v1/contracts/lib/AddressSet.sol
- Improve AddressSet
- Correct comment in Module.sol
> [hebao][audit] Issue 19， 20

- packages/hebao_v1/contracts/base/BaseVault.sol
- packages/hebao_v1/contracts/iface/Vault.sol
The following changes are included:
1. Add a nonce to transactions in BaseVault to prevent replay attacks.
2. Prevent adding more owners than MAX_OWNER.
> [hebao][audit] Issue 1, 16

- packages/hebao_v1/contracts/base/DataStore.sol
- packages/hebao_v1/contracts/stores/PriceCacheStore.sol
- packages/hebao_v1/contracts/stores/QuotaStore.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
- packages/hebao_v1/contracts/stores/WhitelistStore.sol
Only allow a wallet's module to change DataStore state.
> [hebao] improve datastore security

- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
1) require(gas.recipient == controller.collectTo)
2) if method == unlock or method == unlock, reimbursable = false
> [hebao_v1]gas recipient refine

- packages/hebao_v1/contracts/stores/HashStore.sol
- packages/hebao_v1/contracts/version1.1/ControllerImpl.sol
- packages/hebao_v1/contracts/version1.1/base/BaseModule.sol
- packages/hebao_v1/contracts/version1.1/base/MetaTxAware.sol
- packages/hebao_v1/contracts/version1.1/base/MetaTxModule.sol
- packages/hebao_v1/contracts/version1.1/core/ForwarderModule.sol
- packages/hebao_v1/contracts/version1.1/core/WalletFactoryModule.sol
- packages/hebao_v1/contracts/version1.1/security/GuardianModule.sol
- packages/hebao_v1/contracts/version1.1/security/SignedRequest.sol
- packages/hebao_v1/contracts/version1.1/security/WhitelistModule.sol
- packages/hebao_v1/contracts/version1.1/transfers/ApprovedTransferModule.sol
- packages/hebao_v1/contracts/version1.1/transfers/QuotaTransferModule.sol
- packages/hebao_v1/migrations/6_stores.js
- packages/hebao_v1/migrations/7_controller.js
Before this PR, wallet (owner) cannot sign a meta-transaction before enough guardians provide their signatures. With this PR, wallet owner and guardians can sign against the same hash.
> [Hebao_1.1] Allow signing of meta-transactions before necessary datas are all prepared.

- packages/hebao_v1/contracts/version1.1/ControllerImpl.sol
- packages/hebao_v1/contracts/version1.1/security/GuardianModule.sol
- packages/hebao_v1/contracts/version1.1/security/SecurityModule.sol
- packages/hebao_v1/migrations/7_controller.js
> [hebao_1.1] make min active guardian configurable

- packages/hebao_v1/contracts/version1.1/ControllerImpl.sol
- packages/hebao_v1/contracts/version1.1/security/GuardianModule.sol
- packages/hebao_v1/contracts/version1.1/security/SecurityModule.sol
- packages/hebao_v1/migrations/7_controller.js
This reverts commit 3b24fd4336d4ee16b79c16e624b6b5d267c2cecc.
> Revert "[hebao_1.1] make min active guardian configurable (#1385)"

- packages/hebao_v1/contracts/modules/ControllerImpl.sol
- packages/hebao_v1/deployment/1.1.0/build-all-flattened.sh
- packages/hebao_v1/migrations/7_controller.js
> [hebao_v1] refine ControllerImpl to avoid 'stack too deep' error 

- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/contracts/base/ModuleRegistryImpl.sol
- packages/hebao_v1/contracts/base/WalletRegistryImpl.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/UpgraderModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SignedRequest.sol
- packages/hebao_v1/test/helpers/MetaTx.ts
- packages/hebao_v1/test/testInheritance.ts
- packages/hebao_v1/test/testMetaTransactions.ts
- packages/hebao_v1/test/testRecovery.ts
- Enforce that wallet owners must be EOA, and inheritors must be wallets.
- 'inherit' is the process of choosing an EOA to become the wallet's new owner, not the wallet's own address.
> [Hebao_1.1] imporove inheritance module

- packages/loopring_v3/contracts/thirdparty/Proxy.sol
@Brechtpd please let me know if this change is correct.
> [Loopring_3.6] fixed proxy compile warnings

- packages/hebao_v1/contracts/thirdparty/ens/BaseENSManager.sol
> [hebao_1.1] Update BaseENSManager.sol by removing num-of-manager check

- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/PackedCoreModule.sol
- packages/hebao_v1/contracts/modules/core/UpgraderModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/PackedSecurityModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/PackedTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/test/helpers/GuardianUtils.ts
- packages/hebao_v1/test/helpers/WhitelistUtils.ts
- packages/hebao_v1/test/testGuardians.ts
- packages/hebao_v1/test/testInheritance.ts
- packages/hebao_v1/test/testQuota.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
All tests pass.
Note:
- If we merge TransferModule into PackedSecurityModule, the code size will be too large to deploy.
> [hebao_1.1] reduce the number of modules from 6 to 3 to further reduce gas

- packages/loopring_v3/contracts/lib/SignatureUtil.sol
> [Loopring_3.6] improve SignatureUtil

- packages/hebao_v1/contracts/lib/SignatureUtil.sol
- packages/hebao_v1/contracts/modules/OfficialGuardian.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
Meta-tx fees won't consume daily quota in the following 2 situations:
- the target address is the wallet factory
- the meta-tx has a non-zero txAwareHash (which means at least one signature is required from guardian)
All tests pass
> [hebao_1.1] meta-tx fee do not consume quota in some situations

- packages/loopring_v3.js/src/request_processors/spot_trade_processor.ts
- packages/loopring_v3.js/src/types.ts
- packages/loopring_v3/circuit/Circuits/BaseTransactionCircuit.h
- packages/loopring_v3/circuit/Circuits/SpotTradeCircuit.h
- packages/loopring_v3/circuit/Circuits/UniversalCircuit.h
- packages/loopring_v3/circuit/Gadgets/AccountGadgets.h
- packages/loopring_v3/circuit/Gadgets/MatchingGadgets.h
- packages/loopring_v3/circuit/Gadgets/OrderGadgets.h
- packages/loopring_v3/circuit/Gadgets/StorageGadgets.h
- packages/loopring_v3/circuit/Utils/Data.h
- packages/loopring_v3/circuit/docs/WithdrawCircuit_Understanding.md
- packages/loopring_v3/circuit/test/MatchingTests.cpp
- packages/loopring_v3/circuit/test/MerkleTreeTests.cpp
- packages/loopring_v3/circuit/test/OrderTests.cpp
- packages/loopring_v3/operator/create_block.py
- packages/loopring_v3/operator/state.py
- packages/loopring_v3/test/simulator.ts
- packages/loopring_v3/test/testExchangeRingSettlement.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/types.ts
- #1559 
- https://github.com/Loopring/team/issues/102
> [protocol 3.6] Simplify orders (remove validSince, rebate, and allOrNone)

- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeGenesis.sol
@Brechtpd I'm actually not sure this will save gas or not :(
> [Loopring_3.6] use mapping for S.blocks

- packages/loopring_v3/circuit/Circuits/AccountUpdateCircuit.h
- packages/loopring_v3/circuit/Circuits/BaseTransactionCircuit.h
- packages/loopring_v3/circuit/Circuits/DepositCircuit.h
- packages/loopring_v3/circuit/Circuits/NoopCircuit.h
- packages/loopring_v3/circuit/Circuits/SpotTradeCircuit.h
- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/circuit/Circuits/UniversalCircuit.h
- packages/loopring_v3/circuit/Circuits/WithdrawCircuit.h
- packages/loopring_v3/operator/state.py
@Brechtpd I'd like to rename the enum to uppercases, but not sure if I should make the changes in State.py as in this PR.
> [Loopring 3.6] rename enum definition in BaseTransactionCircuit.h

- packages/loopring_v3/DESIGN.md
- packages/loopring_v3/contracts/aux/access/LoopringV3Owner.sol
- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/iface/ILoopringV3.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/LoopringV3.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testLoopringV3Owner.ts
Allow the owner of the exchange to stake LRC later but no later than the 10,000 blocks.
> [Loopring_3.6] improve exchange staking

- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/DefaultDepositContract.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeDeposits.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/test/testDefaultDepositContract.ts
- packages/loopring_v3/test/testExchangeAgents.ts
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeNonReentrant.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testExchangeWithdrawalMode.ts
- packages/loopring_v3/test/testLoopringV3Owner.ts
- packages/loopring_v3/test/types.ts
https://github.com/Loopring/team/issues/123
Still allow users to send more ETH than required. The extra ETH will be fees.
> [Loopring 3.6] remove deposit fee

- packages/loopring_v3.js/src/exchange_v3.ts
- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeAdmins.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
- packages/loopring_v3/test/testBlockVerifier.ts
- packages/loopring_v3/test/testDelayedOwner.ts
- packages/loopring_v3/test/testExchangeBlocks.ts
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeUtil.ts
> [Loopring 3.6] skip fee distribution in submitBlocks

- packages/hebao_v1/.gitignore
- packages/hebao_v1/computeAddress.js
Usage: node computeAddress.js
verify: https://etherscan.io/address/0x0c8dBFB40A324674AD26fe7AecCd4C654036Aa82#readContract
> [hebao1.1.5] Add script for computing blank wallet address offchain

- packages/hebao_v1/.gitignore
- packages/hebao_v1/computeAddress.js
See the best and worst 1000 addresses from the first 100 million salts :
https://github.com/Loopring/team/pull/132
> [hebao_1.1] Optimize address scoring algorithm

- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/test/testExchangeAMM.ts
- packages/loopring_v3/test/testExchangeUtil.ts
> [protocol 3.6] Disable transfers to active AMM tokens

- packages/loopring_v3/contracts/lib/SignatureUtil.sol
I noticed signatures were more expensive than I expected. The reason is that we always got into the slow path where `data.length == 32` where the signature is checked twice (and we only really care about the hash case as far as I can tell in almost all scenarios). 
This PR just enforces the caller to call the correct function (bytes vs bytes32), which I think shouldn't be a problem.
Gas saved: 11,262 -> 6,208 per normal EOA signature check.
An additional ~800 gas can be saved by removing `signer.isContract()` (which uses `extcodehash` which costs 700 gas) and switching back to the old method where an extra `SignatureType.WALLET` byte is added when ERC1271 needs to be used. I don't know why this was changed so I have not done that yet.
(have not run all tests yet)
> [protocol+hebao] Optimize signature checking

- packages/hebao_v1/contracts/lib/ERC1271.sol
- packages/hebao_v1/contracts/lib/SignatureUtil.sol
- packages/hebao_v1/contracts/modules/OfficialGuardian.sol
- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/test/testERC1271Module.ts
No longer support the deprecated version of ERC1271
> [hebao] Update SignatureUtil and ERC1271 support

- packages/loopring_v3/circuit/Circuits/AccountUpdateCircuit.h
- packages/loopring_v3/circuit/Utils/Data.h
- packages/loopring_v3/operator/create_block.py
- packages/loopring_v3/test/testExchangeAccounts.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/types.ts
https://github.com/Loopring/team/issues/140
> [protocol 3.6] Add maxFee to account update

- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitRequest.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
Small fixes for #1816 and I think a small simplification for forced exits.
> [AMM] Small fixes/simplification

- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/LoopringAmmSharedConfig.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUpdateProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
- packages/loopring_v3/contracts/aux/access/LoopringIOExchangeOwner.sol
- packages/loopring_v3/contracts/lib/Drainable.sol
Not sure why all lib functions were made internal, but the warning is back again that the pool contract is too big (also on the master).
> [AMM] Small fixes/improvements

- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmBlockReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmPoolToken.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
Use one state variable to calculate totalSupply instead of two.
> [Loopring AMM] minor improvements

- packages/loopring_v3/contracts/aux/agents/AgentRegistry.sol
- packages/loopring_v3/test/testExchangeAgents.ts
See issue:https://github.com/Loopring/protocols/issues/1824
> [Loopring 3.6] disallow not trusting universal agents

- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/contracts/amm/libamm/AmmBlockReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUpdateProcess.sol
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testAMMPool.ts
- packages/loopring_v3/test/testExchangeAMM.ts
> [protocol3.6] Allow transfers to non-zero AMM weight tokens

- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testExchangeUtil.ts
> [protocol3.6] Fix test

- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
so that relayer can process them differently.
> [Loopring 3.6] Add category to Withdrawal events

- packages/loopring_v3/DESIGN.md
- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitRequest.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinRequest.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AmmUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testAMMPool.ts
- packages/loopring_v3/test/testExchangeUtil.ts
Charge a fixed amount of exit fee using the last token.
> [Loopring AMM] enable exit fees and remove join fees

- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
- Allow wallet owner to specify the inheritance waiting period (2 months to 10 years)
> [hebao 1.2] #3 Customize inheritence waiting period

- packages/hebao_v1/contracts/modules/aux/AddOfficialGuardianModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/contracts/stores/Data.sol
- packages/hebao_v1/contracts/stores/GuardianStore.sol
@Brechtpd I find this implementation is clearer than the current one with two timestamps (validUntil and validSince)
> Further Improve security store impl

- packages/hebao_v1/contracts/base/Controller.sol
- packages/hebao_v1/contracts/modules/ControllerImpl.sol
- packages/hebao_v1/contracts/modules/aux/AddOfficialGuardianModule.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/contracts/modules/core/FinalCoreModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/FinalSecurityModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/FinalTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/migrations/7_controller.js
> [hebao 1.2] Immutable stores in modules

- packages/loopring_v3/contracts/amm/LoopringAmmFactory.sol
- packages/loopring_v3/contracts/aux/access/SelectorBasedAccessManager.sol
- packages/loopring_v3/contracts/aux/agents/OpenGSN2Agent.sol
- packages/loopring_v3/contracts/aux/fast-withdrawal/FastWithdrawalLiquidityProvider.sol
- packages/loopring_v3/contracts/aux/fee-vault/IProtocolFeeVault.sol
- packages/loopring_v3/contracts/aux/fee-vault/ProtocolFeeVault.sol
- packages/loopring_v3/contracts/aux/token-sellers/UniswapTokenSeller.sol
- packages/loopring_v3/contracts/core/iface/ILoopringV3.sol
- packages/loopring_v3/contracts/core/impl/LoopringV3.sol
- packages/loopring_v3/contracts/staking/IUserStakingPool.sol
- packages/loopring_v3/contracts/staking/UserStakingPool.sol
- packages/loopring_v3/contracts/thirdparty/opengsn2/BaseRelayRecipient.sol
#1979 
Not much to do here because most contracts are behind proxies.
> [protocols] Start using immutable

- packages/loopring_v3.js/src/request_processors/account_update_processor.ts
- packages/loopring_v3/circuit/Circuits/AccountUpdateCircuit.h
- packages/loopring_v3/circuit/Utils/Data.h
- packages/loopring_v3/operator/state.py
- packages/loopring_v3/test/simulator.ts
- packages/loopring_v3/test/testExchangeAccounts.ts
- packages/loopring_v3/test/testExchangeUtil.ts
https://github.com/Loopring/team/issues/147
Less changes needed than I thought, so seems like a good change regardless if it will be used a lot or not.
> [protocol 3.6] Allow initializing owner with account update txs

- packages/hebao_v1/contracts/modules/ControllerImpl.sol
- packages/hebao_v1/contracts/modules/aux/AddOfficialGuardianModule.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/core/FinalCoreModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/FinalSecurityModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/SignedRequest.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/FinalTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/test/testInheritance.ts
I still need time to review all Stores, GuardianModule, GuardianUtil, SecurityModule, and ForwarderModule
> [hebao 1.2] minor improvements and cleanups -part 1

- packages/loopring_v3/util/find_optimal_poseidon.py
Adding missing script to find the "optimal" posseidon parameters depending on the number of values that need to be hashed.
> [protocol 3.6] Add missing script to find optimal poseidon

- packages/hebao_v1/contracts/modules/ControllerImpl.sol
- packages/hebao_v1/contracts/modules/WalletImpl.sol
- packages/hebao_v1/contracts/price/CachedPriceOracle.sol
- packages/hebao_v1/deployment/flatten-all.sh
- packages/hebao_v1/test/helpers/Artifacts.ts
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
- packages/hebao_v1/test/testUpgrader.ts
Controller must use CachedPriceOracle
> [hebao 1.2] price oracle is now immutable

- packages/hebao_v1/computeAddress.js
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
> [Hebao1.2] fix UpgraderModule and computeAddress.js

- packages/loopring_v3/DESIGN.md
- packages/loopring_v3/contracts/core/iface/IBlockVerifier.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/BlockVerifier.sol
- packages/loopring_v3/contracts/core/impl/DefaultDepositContract.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBalances.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeTokens.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/BlockReader.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
We'll follow the following steps for the different owners of security critical contracts:
- Loopring will launch with a multi sig.
- Loopring will either switch to a DAO or add an additional delay contract so any update is transparent and people have time to exit: https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/contracts/aux/access/BlockVerifierOwner.sol
Added extra documentation to the design doc with mitigation strategy.
Removed in previous PR.
Although we can allow anyone to submit blocks: https://github.com/Loopring/protocols/blob/c48831bde95b9e59a32e9b4ae36316238a650cc3/packages/loopring_v3/contracts/aux/access/LoopringIOExchangeOwner.sol#L58
we currently don't have any open source software that third party operators can use to process withdrawals. Concrete …
> [protocol 3.6] Audit feedback

- packages/loopring_v3/circuit/Gadgets/MatchingGadgets.h
- packages/loopring_v3/circuit/test/MatchingTests.cpp
- packages/loopring_v3/test/testExchangeAMM.ts
#2058 
Increases max range of ratio to 2**(96*2-14).
> [protocol 3.6] AMM range check fix

- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/test/testWalletCreation.ts
https://blog.trailofbits.com/2020/12/16/breaking-aave-upgradeability/
> [hebao] Disable initializing the wallet implementation contract

- packages/loopring_v3/fee-regression/linear_regression.py
#2196 
Not sure at all if these are currently correct, will verify tomorrow.
With current values:
```
- withdrawal_cost:     45050
- transfer_cost:       2150
- trade_cost:          2700
- account_update_cost: 16050
- amm_join_exit_cost:  100650
```
> Businessify fee linear regression

- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinRequest.sol
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testAMMPool.ts
> [protocol 3.6] Add AMM join fee

- packages/hebao_v2/script/deploy-arbitrum.ts
- packages/hebao_v2/script/deploy-optimistic.ts
- packages/hebao_v2/test/commons.ts
- packages/hebao_v2/test/helper/Constants.ts
- packages/hebao_v2/test/walletFactory.spec.ts
create wallet on arbitrum succeeded:
https://explorer.arbitrum.io/#/tx/0x0772694c31784e259531c408f6a23253ba28ccada2cf2b064e201f2e524bd3a3
> arbitrum-deploy-fix

- packages/hebao_v2/contracts/base/libwallet/ApprovalLib.sol
- packages/hebao_v2/contracts/base/libwallet/MetaTxLib.sol
- packages/hebao_v2/contracts/base/libwallet/WalletData.sol
MetaTx can be replayed if  metaTx.nonce = 0 and didn't call a *WA method.
> Hebaov2 metatx fix (replay bug)

- packages/hebao_v2/contracts/base/libwallet/MetaTxLib.sol
- packages/hebao_v2/contracts/base/libwallet/WalletData.sol
@Brechtpd, After some discussion with Daniel, we believe that gas saving is also important even for L2. So I revert the previous changes and add some extra checks to the metaTx.nonce. please take another look.
> [hebaov2] metatx nonce check reinforcement

- packages/loopring_v3/contracts/converters/BaseConverter.sol
- packages/loopring_v3/test/testBridge.ts
- packages/loopring_v3/test/testExchangeUtil.ts
> [Protocol 3.7] minor_improvement test fixes

- packages/hebao_v2/test/helper/Bitstream.ts
- packages/hebao_v2/test/helper/Signature.ts
- packages/hebao_v2/test/helper/eip712.ts
- packages/loopring_v3/package.json
> Update package json test fixes

- packages/hebao_v2/contracts/base/SmartWallet.sol
- packages/hebao_v2/hardhat.config.ts
- packages/hebao_v2/test/blankWallet.spec.ts
- packages/hebao_v2/test/commons.ts
- packages/hebao_v2/test/helper/Constants.ts
- packages/hebao_v2/test/recover.spec.ts
gas costs:
- createWallet ( with one guardian)：235000 gas
- setOwner: 30500 gas
> [hebao_v2] blank wallet creation support

- packages/hebao_v2/hardhat.config.ts
- packages/hebao_v2/package.json
- packages/hebao_v2/script/deploy-and-setup.ts
Deployment result on goerli testnet:
* walletFactory: 0x9B8855374fd91c637D9D79a2673f35D4e19639DE
* masterCopy: 0x95BFC1BE625218B5798A2A4BAe23002d8fBEbeB7
* officialGuardian: 0xF7410703dB972eF5926A6f5514D3d87fBb697D49
> [hebaov2] deploy on goerli testnet and add etherscan plugin

- packages/counterfactual_nft/package.json
- packages/counterfactual_nft/scripts/computeAddress.js
> [counterfactual_nft] add script to compute NFT contract address

- packages/counterfactual_nft/README.md
> Minor grammar fix

- packages/loopring_v3/BACKEND.md
Minor grammar fix at line 7. Minor spelling fix at line 25
> Minor grammar and spelling fixes

- packages/loopring_v3/contracts/aux/fast-withdrawal/FastWithdrawalLiquidityProvider.sol
Remove extra whitespace at line 55
> Remove extra whitespace

- packages/counterfactual_nft/contracts/OpenseaSupport.sol
It looks like the `_setCreator` function was unused.  Added its usage in `setCreator`
> Using internal function for creator assignment.
