Loopring/protocols

- packages/loopring_v3/contracts/lib/RoleBasedOperators.sol
For our DAO, the reputation token should be minted/destroyed over time by multiple contracts including DEX instances, the Loopring contract, UserStakingPools, as well as the DAO itself. This contract introduced a way to allow multiple authorized addresses, or operators, to mint/destroy LOOP tokens.
> [Protocol3] Add RoleBasedOperators.sol for DAO management

- packages/loopring_v2/deployment-source/v2.2-dolomite/RingSubmitter_flat.sol
This contains the two changes we need to launch Dolomite on v2 of Loopring:
1. disabling margin splitting
2. Emitting an event when there is a `waiveFeePercentage < 0`
After talking to @Brechtpd , we decided the easiest way to go about this, was to emit an event when there is a negative `waiveFeePercentage`. It was easiest to add the event to the `Library` and change the function declarations to no longer be `view`s.
This was tested via Ganache & Dolomite's backend in Scala. If the proposed changes are okay, can you redeploy this contract? Once it's deployed, Dolomite will be able to settle trades on the mainnet and we'll be ready to launch :)
> [Protocol2] Made the two updates necessary for Dolomite's launch & re-deployment

- package.json
bug split version: lodash [fix:](https://github.com/lerna/lerna/commit/c405871)
reference: 
https://github.com/lerna/lerna/releases/tag/v3.16.0
> update lerna v3.16.0

- packages/loopring_v3/test/testExchangeMaintenanceMode.ts
- packages/loopring_v3/test/testLoopring.ts
After this PR only `testExchangeNonReentrant` has one test failure.
> [Protocol3] fixes test failures

- packages/loopring_v3/README.md
- packages/loopring_v3/circuit/CMakeLists.txt
- packages/loopring_v3/operator/state.py
- packages/loopring_v3/package.json
- packages/loopring_v3/test/simulator.ts
- packages/loopring_v3/test/testExchangeCancel.ts
- packages/loopring_v3/test/testExchangeRingSettlement.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- The circuits testing executable is made with `make`. All tests can be run with `npm run test-circuits`.
- The rounding error check is now done on the rate of the actual trade (fillS/fillB) instead of on the rounding error on the division to calculate `fillB`. This should be more accurate and is cheaper.
- When cancelling an order with an `orderID` > `tradingHistory.orderID` the filled amount is reset to 0. This accurately represent the filled amount of the `orderID` stored in the trading history (but the order is cancelled, so it doesn't actually matter for the protocol).
> [Protocol3] Added circuit testing support + small improvements

- packages/lightcone_v2.js/src/sign/exchange.ts
If we use ```config.getGasLimitByType("eth_transfer").gasLimit```, it will return an error: 
```
"Error: base fee exceeds gas limit
at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1851624
at /usr/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:21647
at process._tickCallback (internal/process/next_tick.js:61:11)"
```
> [Lightcone_V2.js] Update the value of gasLimit in exchange.ts in lightcone_v2.js

- packages/loopring_v3/contracts/iface/IExchange.sol
- packages/loopring_v3/contracts/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeData.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeGenesis.sol
- packages/loopring_v3/test/testExchangeUtil.ts
Moving the genesis block value to ExchangeV3 will enable us to reuse ExchangeData for exchanges with different tree height/depth configurations.
> [Protocol3] Move genesis hash to Exchange.sol

- packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/test/testExchangeBlocks.ts
A safety check I forgot to add for the input aliasing exploit.
This one could actually be dangerous if the value >= SNARK_FIELD gets stored onchain. In withdrawal mode we compare the computed value against the value stored on-chain.
> [Protocol3] Added check for new Merkle root value

- packages/lightcone_v2.js/src/sign/exchange.ts
> [Lightcone_v2.js] Fix missing 'to' when using Transaction in create account method

- packages/loopring_v3/contracts/impl/UniversalRegistry.sol
Address are 20 bytes, we can save the two bools within the protocol address and we can save 20.000 gas if the version string is less than 12 bytes long. I would also consider making the version a number (uint96)
> Save gas cost in universal registry

- packages/loopring_v3/contracts/impl/UserStakingPool.sol
Unix timestamps can be no bigger than ~uint40, using uint64 for the timestamps reduces gas cost for every store of the Staking struct by 20.000 gas.
> [protocol3] Reduce gas cost by 20.000 gas

- packages/lightcone_v2.js/src/lib/sign/eddsa.ts
- packages/lightcone_v2.js/src/sign/exchange.ts
- packages/lightcone_v2.js/test/testEddsa.ts
- packages/lightcone_v2.js/tsconfig.json
1. Fix eddsa verify function and add a simple unit test.
2. Align data with python eddsa implemention used for market maker.
Signed-off-by: yue.wang <yue.wang@loopring>
The verify did not work before, so market maker's orders which were badly signed ruin the on-chain status and lead to roll back. This PR tries to enable verify on js and make data align with python eddsa which is used by Hummingbot.
> [Lightcone_v2.js] Fix eddsa verification function.

- packages/lightcone_v2.js/src/lib/sign/bitarray.ts
Our old private key seems too short.
Before:
keyPair: {
publicKeyX:"15030727036724168751212480282500540869268142725392913493575803542173309367534",
publicKeyY:"21709653362655094841217318150615954140561437115749994376567240539798473592233",
secretKey: "1268930117" #too short for private key
}
After:
{ publicKeyX:'8813841639841077546078089488867097267085213881825607563506983828135503562052',
publicKeyY:'20955895273353568600806208646961956684700918435341245662365898050978330578659',
secretKey:'1696716368835402715786292139526618358846458481981228831374151359817119808723' 
}
Use sha256 here may not fully comply with the wiki page, but key length strength should be enough.
> Update bitarray hash algorithm to avoid short private key.

- packages/lightcone_v2.js/globals.d.ts
- packages/lightcone_v2.js/package.json
- packages/lightcone_v2.js/src/index.ts
- packages/lightcone_v2.js/src/lib/wallet/config/config.json
- packages/lightcone_v2.js/src/lib/wallet/config/index.ts
- packages/lightcone_v2.js/src/lib/wallet/ethereum/metaMask.ts
- packages/lightcone_v2.js/src/lib/wallet/ethereum/transaction.ts
- packages/lightcone_v2.js/src/lib/wallet/ethereum/utils.ts
- packages/lightcone_v2.js/src/lib/wallet/ethereum/walletAccount.ts
- packages/lightcone_v2.js/src/sign/exchange.ts
- packages/lightcone_v2.js/src/wallet/account.ts
- packages/lightcone_v2.js/test/testAccount.ts
- packages/lightcone_v2.js/test/testEddsa.ts
- packages/lightcone_v2.js/test/testExchange.ts
```npm run test``` doesn't pass
```
####################################
[ 18461811482240861092127996284914078088723463759234691728583091886124032327996n,
12408252482010503600595715827901878671968894948988357460202767969927793637775n ]
1687023508745541781822008154827904514028415203517821866372277605910974068776n
accP: 
12814186605633838161465901630320439100565827976101287594230038579582678591406
20581441827076388071492824916932778097249385119747029565502024772738923615041
2) sign and verify
accP: 
4496886077546369029288375509585003717020710202480852367695556545173931953798
7963252827810179549682475526859097309220865080725729373845158239060043994495
✓ verify python gen sig (609ms)
3) generate key pair
eddsa sign test
4) create account
6 passing (3s)
4 failing
1) account test
"before each" …
```
> [Lightcone_v2.js] Fix npm build due to dependency updates

- packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/package-lock.json
Caused 63 test failures. I think we should revert this change for now.
> REVERT [Protocol3] emit BlockFinalized event only once (#614)

- packages/loopring_v3/test/testExchangeBlocks.ts
After constant value review, few const were not covered by the test.
Add 2 cases for MAX_GAP_BETWEEN_FINALIZED_AND_VERIFIED_BLOCKS and MIN_AGE_PROTOCOL_FEES_UNTIL_UPDATED.
However as MAX_GAP_BETWEEN_FINALIZED_AND_VERIFIED_BLOCKS now is 2500, it takes ~200s to complete, so far the case is skipped and it can be enabled after MAX_GAP_BETWEEN_FINALIZED_AND_VERIFIED_BLOCKS becomes small.
> [Protocol3] Add missed const cases

- packages/loopring_v3/test/testExchangeBlockPermutations.ts
- packages/loopring_v3/test/testExchangeUtil.ts
This works around the limitation in the new circuits that the fills cannot be 0. I forgot that this is actually a case where that would be useful.
Luckily  the workaround isn't very difficult. We can can just create orders for the dummy account that for example self-trades 1 wei LRC for 1 wei ETH. So the only difference for the relayer should be that the dummy orders have some different properties and that the dummy account needs e.g. 1 wei LRC and 1 wei ETH in its account (this only needs to be deposited once). The dummy ring can then be used, as is, `2**96` times, so there will be no need to ever create another dummy ring or another dummy account.
A minor downside is that the dummy ring now cost 24 gas more/dummy trade (but the compression could help with this), but this is pretty …
> [Protocol3] Fixed dummy rings

- packages/loopring_v3/contracts/iface/IBlockVerifier.sol
- packages/loopring_v3/contracts/iface/IDelayedOwner.sol
- packages/loopring_v3/contracts/impl/BlockVerifier.sol
- packages/loopring_v3/contracts/impl/owners/BlockVerifierOwner.sol
- packages/loopring_v3/contracts/impl/owners/DelayedOwner.sol
- packages/loopring_v3/contracts/impl/owners/ImplementationManagerOwner.sol
- packages/loopring_v3/contracts/impl/owners/LoopringV3Owner.sol
- packages/loopring_v3/contracts/lib/BytesUtil.sol
- packages/loopring_v3/contracts/test/DelayedOwnerContract.sol
- packages/loopring_v3/contracts/test/DelayedTargetContract.sol
- packages/loopring_v3/test/testDelayedOwner.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/util/Artifacts.ts
On our current smart contracts there are some critical values that the owner of the contract could immediately change (like changing the verification keys so proofs can be constructed using any rules) which is a big security issues for users.
This PR has a simple base contract that enforces a mandatory delay on specified function calls. This means that if the owner of a contract is malicious, users can observe the malicious intent and act before the function call actually can be executed.
In the future this can be done with more advanced mechanisms like a DAO, but this seems to be a good compromise between security/simplicity in the short/medium term.
> [Protocol3] Add owner contracts with mandatory delays

- packages/tokenbank_v1/contracts/base/BaseModule.sol
- packages/tokenbank_v1/contracts/base/BaseWallet.sol
- packages/tokenbank_v1/contracts/base/MetaTxModule.sol
- packages/tokenbank_v1/contracts/lib/ReentrancyGuard.sol
- packages/tokenbank_v1/contracts/modules/loopring/ExchangeModule.sol
- packages/tokenbank_v1/contracts/modules/security/GuardianModule.sol
- packages/tokenbank_v1/contracts/modules/security/LockModule.sol
- packages/tokenbank_v1/contracts/modules/security/RecoveryModule.sol
- packages/tokenbank_v1/contracts/modules/transfers/ApprovedTransfers.sol
- packages/tokenbank_v1/contracts/modules/upgrade/UpgraderModule.sol
Some changes so that re-entrancy is easier (hopefully). It should also fix some interactions between the wallet and module that wouldn't work with the current code:
```
addModule (wallet, nonReentrant)
activate (module)
bindStaticMethod (wallet, nonReentrant - fails because re-entrancy is detected)
```
I think the cleanest solution to this is that all communications wallet <-> modules are inherently safe because all code is written/approved by us. So if a wallet function is `onlyModule` it's safe, if a module function is `onlyFromWallet` it is also safe (`transact` is also only callable by a module, and only with a select number of functions known beforehand. If this would not be the case we would have to make sure `transact` can't call a function on a module directly, otherwise it would …
> [tokenbank] Some re-entrancy changes

- packages/hebao_v1/contracts/base/BaseModule.sol
- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/contracts/base/ERC1271Module.sol
- packages/hebao_v1/contracts/base/WalletFactory.sol
- packages/hebao_v1/contracts/iface/Wallet.sol
- packages/hebao_v1/contracts/modules/dapps/UniswapModule.sol
- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/LockModule.sol
- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/TokenBalances.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
I'm still not completely happy with this PR (adding/removing modules is less clean than before), but I do think the positives far outweigh the negatives.
With the current code the module can call into the module for activation/deactivation, which kind of complicates things a bit. In the best case, which makes things easier, everything is callable using `transact` or the fallback function without any limitations or caveats. The current exceptions are `activation` and `deactivation` which should not be callable by the wallet except when adding/removing modules. 
To solve this in this PR the wallet doesn't call `activate` and `deactivate` any more, those can now be called by the module adding/removing the module. This also means that the wallet itself has zero dependencies on modules. A …
> [hebao] Changes to module activation/deactivation

- packages/hebao_v1/contracts/base/BaseWallet.sol
See here for more info:
- https://github.com/gnosis/safe-contracts/issues/149
This is to ensure the smart wallet can still be used to receive ETH with `send`/`transfer` after Istanbul.
> [hebao] Work around Istanbul gas cost changes for send/transfer

- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/RecoveryModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/transfers/ApprovedTransfers.sol
A meta transaction needs to be signed by a trusted signer, otherwise anyone can create a meta tx for a wallet and spend funds on gas reimbursement. This signers need to be checked before the meta-tx `call` is executed because the `call` is allowed to fail.
Not really sure if this is the best solution.
> [hebao] Better meta transaction authorization checks

- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianUtils.sol
- packages/hebao_v1/contracts/modules/security/RecoveryModule.sol
- packages/hebao_v1/contracts/modules/transfers/ApprovedTransfers.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
The basic idea is to store data about the guardian and let modules use that data for more complex logic. This way we do not limit ourselves to a single system which we're than stuck with. So storing the guardians and adding/removing guardians remains just as easy as before, there's just a single extra `uint` value stored for each guardian. The modules could store any data in it, but currently it's used as a bitmask to store some extra data about the guardian.
This means there's a bit more work to 'prepare' the guardians, but that's insignificant with checking the actual signatures of the guardians. It allows a lot of flexibility in the modules (like allow a self controlled hardware guardian to do transfers with the same quota as the wallet owner or something like that).
I also changed …
> [hebao] Guardian grouping

- packages/hebao_v1/contracts/base/MetaTxModule.sol
- packages/hebao_v1/contracts/base/WalletFactory.sol
- packages/hebao_v1/contracts/modules/core/WalletFactoryModule.sol
- packages/hebao_v1/contracts/modules/security/LockModule.sol
- packages/hebao_v1/contracts/thirdparty/Create2.sol
The current method doesn't allow the wallet owner to create the wallet himself (which can be a security risk if he already deposited funds to the address) or easily allow the wallet owner to pay for the wallet deployment cost.
This PR allows the future wallet owner to remain in control of his wallet at any time. He can either deploy the wallet himself (by calling the create function directly) or pay a relayer to do it for him using a meta transaction.
So the normal process would be something like this:
- The user downloads the wallet UI and the wallet UI creates a new owner keypair.
- The wallet UI computes the wallet address and shows the address in the UI.
- The user can now deposit ETH/any token to the wallet address anytime he wants.
- The wallet UI monitors the deposits. If the user …
> [heabo] Allow the wallet to be created trustlessly (with meta tx or not)

- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/stores/QuotaStore.sol
- Changed to a rolling daily limit instead of a hard day limit. The daily rolling limit is time zone independent and has some better worst case properties (with a hard day limit the daily limit be spent twice very shortly when done at 23.59 and 00.00, this is never possible with the rolling limit as the amount that can be spent gradually increases). The worst case (when hacked) is the same for both methods in that in 24 hours the daily limit can be spent twice.
- Allow the time it takes to change the daily quota to be set by the module. This allows for more flexible modules, which is used here to change the daily limit immediately with a majority.
> [hebao] Some small quota implementation changes

- packages/hebao_v1/contracts/base/ControllerImpl.sol
- packages/hebao_v1/contracts/iface/Controller.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/stores/PriceCacheStore.sol
- Token price caching shouldn't be done automatically when doing a transaction for a user. This will greatly increase the gas consumption of the user's transaction which will either make the transaction fail or the user ends up paying a lot more in gas than expected. In both cases it's the user that pays for it.
- The modules themselves only need to communicate with a `PriceOracle`, all caching can be hidden behind that interface. There's no need for the main smart wallets to have access to the `DataStore`. Price updates need to be started by an external party and how this is done for different tokens (manual price setting vs oracle vs public function anyone can call) can be programmed in a manager contract for example. Maybe we can even use [the system Compound is …
> [hebao] Some small changes for price caching

- packages/hebao_v1/contracts/iface/Data.sol
- packages/hebao_v1/contracts/modules/core/WalletUpgraderModule.sol
- packages/hebao_v1/contracts/modules/dapps/LRCStakingModule.sol
- packages/hebao_v1/contracts/modules/dapps/base/GenericDAppModule.sol
- packages/hebao_v1/contracts/modules/exchanges/LoopringModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianUtils.sol
- packages/hebao_v1/contracts/modules/security/QuotaModule.sol
- packages/hebao_v1/contracts/modules/security/RecoveryModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/ApprovedTransfers.sol
- packages/hebao_v1/contracts/modules/transfers/QuotaTransfers.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
Instead of using enums with specific names for guardian groups, which we don't use, I just changed it so that it's possible to put a guardian in a certain group (nameless). The group decides which rules to follow:
- Group 0: No grouping (1 vote/guardian)
- Groups [1, 5]: Single guardian needed per group
- Groups [6, 10]: Half the guardians needed per group
- Groups [11, 15]: A majority of guardians needed per group
The reason for this fixed group ordering is that it makes counting the number of votes very easy and there's no need for an unlimited number of groups.
This way we don't try to make decisions on-chain what to do with certain types of guardians because this ended up being harder than expected (I don't believe there are universal rules that always work best for this). The user/UI …
> [hebao] Guardian refactoring

- packages/hebao_v1/contracts/base/MetaTxModule.sol
- If there is no fee recipient, people can monitor the transaction pool and do the same transaction with slightly higher gas price and receive all the fees for executing the transaction. To prevent the relayer from being front-run (and wasting gas for trying to do a meta transaction that is already executed) the fee recipient is signed by the user. 
- If `feeRecipient == address(0)` the current behaviour is kept: anyone can do the transaction and reimbursement is sent to `msg.sender`.
- In general could be helpful to set a certain address anyway to receive the payments.
> [hebao] Added fee recipient to meta transaction

- packages/loopring_v3.js/index.ts
- packages/loopring_v3.js/package.json
loopring_v3.js version 0.5.2 has been published to npmjs, and used by dexbrowser
> update version of loopring_v3.js, and publish it to npmjs

- packages/hebao_v1/genAbi.sh
The genAbi.sh script was not working due to an issue of solc-js: https://github.com/ethereum/solc-js/issues/114, So I change it to solc.
You will have to install solc@0.6 first, on mac just run `brew install ethereum/ethereum/solidity`.
> [HEBAO] update genAbi.sh

- .gitmodules
- packages/loopring_v3/Makefile
- packages/loopring_v3/circuit/CMakeLists.txt
- packages/loopring_v3/package-lock.json
- packages/loopring_v3/package.json
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testLoopringV3Owner.ts
- packages/loopring_v3/test/testUniversalRegistry.ts
This PR (together with the circuits PR, all on the `mcl` branch) contains the following optimizations:
- **Switched to the [mcl](https://github.com/herumi/mcl) library for curve operations.** This is also what was basically discussed in #291, but I do not use any branch of SECBIT because those branches have some issues (large diffs because of formatting changes, introduces some bugs even for standard alt_bn254). The main integration code is the same to let libsnark make use of the lib (which was mainly written by herumi himself, the author of mcl), but that's it. Other changes are minimal. The result is 2x-3x faster multi exponentiations, resulting in ~50% faster proving times (but we have some overhead so this was much less, see below). The only thing we have to do to make use of this is …
> [Protocol3] Prover optimizations

- packages/loopring_v3/contracts/impl/ProtocolFeeVault.sol
- packages/loopring_v3/contracts/impl/UniswapTokenSeller.sol
@see https://solidity.readthedocs.io/en/v0.5.11/contracts.html#fallback-function
> [LoopringV3] fix a bug that ProtocolFeeVault and UniswapTokenSeller contract can not accept eth

- .gitmodules
- packages/loopring_v3/README.md
- packages/loopring_v3/globals.d.ts
- packages/loopring_v3/package.json
- packages/loopring_v3/test/testBlockVerifier.ts
- packages/loopring_v3/test/testDelayedOwner.ts
- packages/loopring_v3/test/testExchangeAdmin.ts
- packages/loopring_v3/test/testExchangeBlockPermutations.ts
- packages/loopring_v3/test/testExchangeBlocks.ts
- packages/loopring_v3/test/testExchangeCancel.ts
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeInternalTransfer.ts
- packages/loopring_v3/test/testExchangeMaintenanceMode.ts
- packages/loopring_v3/test/testExchangeNonReentrant.ts
- packages/loopring_v3/test/testExchangeRingSettlement.ts
- packages/loopring_v3/test/testExchangeShutdown.ts
- packages/loopring_v3/test/testExchangeTokens.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testExchangeWithdrawalMode.ts
- packages/loopring_v3/test/testLoopring.ts
- packages/loopring_v3/test/testLoopringV3Owner.ts
- packages/loopring_v3/test/testMovingAveragePriceProvider.ts
- packages/loopring_v3/test/testOperator.ts
- packages/loopring_v3/test/testSignatureBasedAddressWhitelist.ts
The next batch of optimizations building on #990. Compared to that version the prover should be about **5x faster on a 16 core CPU and uses 5x less memory** (less than 1GB per 1M constraints). Because of that we can now use a **c5.9xlarge** "compute optimized" instance at **$1.5/hour** to prove a 1024 trade block (currently our biggest circuit with 64M constraints). This instance type even has 18 CPU cores (though currently we can't make really good use of those 2 extra cores, but it already helps a bit).
**A 1024 trades block now only takes 105 seconds to prove on a c5.9xlarge.** Note that because a certain optimization that changes the circuits themselves currently cannot be used without redoing our trusted setup it's actually 5% slower for us now (110 seconds). So not too bad, but …
> [protocol3] Prover optimizations (part 2)

- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/test/testGuardians.ts
It was possible to add as many guardians as one wanted by first adding them all before confirming any of them because the check was against the count of active guardians in the store, and not also the amount of guardians already being added.
The check is moved after the actual addition to the store as this is the easiest and also most correct check possible. Earlier checks, like doing the check in `addGuardian`, would be quite difficult to do 100% correctly and it's not like this check will get triggered in a realistic scenario so this seems fine.
> [hebao] Fix max guardians check

- packages/hebao_v1/contracts/lib/MathInt.sol
Replaced `MathInt` implementation with OpenZeppelin's `SignedSafeMath` implementation as recommended.
> [hebao][Audit] Issue 3

- packages/hebao_v1/contracts/lib/MathUint.sol
- packages/loopring_v3/contracts/lib/MathUint.sol
Removed `decodeFloat` from `MathUint` used in hebao as it is not reusable but Loopring protocol 3 specific. Will create a `Float` library for the protocols later so we don't bloat `MathUint` with it.
Added extra overflow checks for safety in general cases. The floats we decode onchain can't have overflow issues because we only decode floats verified by the circuits, so they are guaranteed `< 2**96`.
> [hebao][Audit] Issue 6

- packages/hebao_v1/contracts/base/MetaTxModule.sol
8. MetaTxModule.sol: Relayer can cause transactions to fail by sending just above the limit the user provided.
Due to the way the VM provides gas to external calls since EIP 150 ws implemented, if the external call is executed with less gas than the ​gasSettings.limit​, only 63/64 of the available gas will be provided, allowing for the relayer to force transactions with a limit lower than the one set by the user.
A discussion around this issue is available at https://github.com/gnosis/safe-contracts/issues/100
Recommendation
Require that the gas available after the call is greater than than 65/64 of the user provided gasSettings.limit.
For reference: Implementation of the fix by the Gnosis Safe team: https://github.com/gnosis/safe-contracts/commit/62d4bd39925db65083b035115d6987772b2d2d ca …
> [hebao][audit] issue 8

- packages/hebao_v1/contracts/modules/security/SignedRequest.sol
- packages/hebao_v1/contracts/stores/HashStore.sol
- packages/hebao_v1/contracts/stores/NonceStore.sol
- packages/hebao_v1/package.json
Adds `onlyWalletModule` in the store functions that need it.
I don't think it's necessary to keep the hashes separate for different wallets in HashStore as long as the hash already has the wallet address mixed in, but I don't think it hurts to do it just in case.
> [hebao] Added onlyWalletModule to HashStore/NonceStore functions

- packages/hebao_v1/contracts/modules/base/MetaTxAware.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
Previously:
Someone can use meta transaction to call `addGuardian` with `nonce=0` and `txAwareHash !=0`, then change the `data` to call the same function with different parameters.
> [Hebao_1.1] fix forwarderModule bug

- packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
I don't have a strong reason why empty blocks should be disabled, but I feel it's wrong to allow different blocks having the same root.
I guess the check may not be necessary if the relayer account's nonce must +1. But I just want to double check.
> [Loopring_3.6] Disable empty blocks

- packages/loopring_v3/contracts/iface/ExchangeData.sol
- packages/loopring_v3/contracts/iface/IBlockVerifier.sol
- packages/loopring_v3/contracts/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/impl/BlockVerifier.sol
- packages/loopring_v3/contracts/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/contracts/impl/libexchange/ExchangeGenesis.sol
Flat the mapping inside BlockVerifier and make accountTreeDepth part of the key calculation.
> [Loopring_3.6] flat BlockVerifier key and include accountTreeDepth

- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/iface/ILoopring.sol
- packages/loopring_v3/contracts/core/iface/IUniversalRegistry.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/LoopringV3.sol
- packages/loopring_v3/contracts/core/impl/UniversalRegistry.sol
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/testUniversalRegistry.ts
#1509, at least what is needed for the new exchange contract. We don't have to build anything more into the protocol, even when using the challenge system we can only allow funds to be transferred from the old exchange to the new exchange contract when `newExchange.getMerkleRoot() == expectedMerkleRoot` and `newExchange.getBlockHeight() == 1`.
> [protocol 3.6] Add custom genesis Merkle root

- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
Mac上文件系统的文件名不区分大小写，所有编译不会出错。ubuntu上会出错。
> [Hebao1.1] Update ForwarderModule.sol

- packages/loopring_v3/contracts/core/iface/IDepositContract.sol
- packages/loopring_v3/contracts/core/impl/DefaultDepositContract.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeDeposits.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
Lets only use "auxilary" word consistently as opposed to DA, and use "extraData" for IDepositContract.
> a few renaming for better readability (tests should also be updated)

- packages/hebao_v1/contracts/base/BaseWallet.sol
` require(methodToModule[_method] == address(0), "METHOD_BOUND_ALREADY");`
This check is unnecessary and will break the upgrading.
> [hebao1.1] Update BaseWallet.sol

- packages/loopring_v3/test/testDelayedOwner.ts
Classic forgetting to `await` which makes tests randomly fail.
> [protocol 3.6] Added missing await

- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
需要先删除module然后再添加。
因为添加ERC1271Module会触发bindMethod，
然后删除老的ERC1271Module的时候，又会触发unbindMethod，导致上一步bindMethod失效。
> [hebao1.1] Fix a bug in UpgraderModule

- packages/hebao_v1/contracts/modules/aux/AddOfficialGuardianModule.sol
- packages/hebao_v1/contracts/modules/aux/OfficialGuardianModule.sol
AddOfficialGuardianModule is a self-removal module whose only job is to add the official guardian as the very first guardian to a newly created wallet.
> [Hebao_1.1] add AddOfficialGuardianModule

- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/circuit/Circuits/WithdrawCircuit.h
- packages/loopring_v3/circuit/Utils/Data.h
- packages/loopring_v3/operator/create_block.py
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeInternalTransfer.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/types.ts
#1688
Currently only supports `fee != maxFee` when using an EdDSA signature. I can add support for it with onchain signatures as well if requested. The reason for this is that only the actual fee is part of the DA, but if `fee != maxFee` we need to calculate the hash for the signature with `maxFee` instead of `fee`, so we need to put the `maxFee` onchain (using the auxiliary data) and check that `fee < maxFee` onchain.
> [protocol 3.6] Add maxFee to withdrawals/transfers

- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/contracts/lib/AddressUtil.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/thirdparty/ens/BaseENSManager.sol
- packages/hebao_v1/legacy/version1.0/contracts/transfers/QuotaTransfers.sol
- packages/hebao_v1/legacy/version1.0/contracts/transfers/TransferModule.sol
- packages/loopring_v3/contracts/lib/AddressUtil.sol
Optimized most frequent paths. In normal cases this only saves ~0.5%-1.0% of gas. Calls with a lot of data will save more gas, but probably quite infrequent.
I do feel like the compiler should be able to do this so we don't have to worry about this. Maybe I'll make an issue on the solidity github.
> [hebao] Optimized memory copies

- packages/loopring_v3.js/src/exchange_v3.ts
- packages/loopring_v3.js/src/request_processors/spot_trade_processor.ts
- packages/loopring_v3.js/src/request_processors/transfer_processor.ts
- packages/loopring_v3.js/src/request_processors/withdrawal_processor.ts
- packages/loopring_v3/DESIGN.md
- packages/loopring_v3/circuit/Circuits/SpotTradeCircuit.h
- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/circuit/Gadgets/MathGadgets.h
- packages/loopring_v3/circuit/Gadgets/StorageGadgets.h
- packages/loopring_v3/circuit/test/StorageTests.cpp
- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/BlockReader.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/test/testExchangeRingSettlement.ts
- packages/loopring_v3/test/testExchangeUtil.ts
https://github.com/Loopring/team/issues/124
Numbers in the design doc updated for the worst case scenario where all bytes are non-zero (like we do for all other data as well), cost will be lower in practice.
> [protocol 3.6] Remove short storageID uses

- packages/loopring_v3/contracts/aux/access/LoopringIOExchangeOwner.sol
> unify submitBlocksCompressedWithCallbacks

- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/DefaultDepositContract.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeDeposits.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
- packages/loopring_v3/contracts/lib/FloatUtil.sol
- packages/loopring_v3/contracts/lib/MathUint.sol
- packages/loopring_v3/contracts/lib/MathUint96.sol
- packages/loopring_v3/contracts/test/AmmPool.sol
- packages/loopring_v3/contracts/thirdparty/SafeCast.sol
#1758 
Hope I didn't miss anything, but I don't think we do a lot of math on uint96 normally.
> [protocol 3.6] uint96 safe math

- packages/loopring_v3/contracts/test/AmmPool.sol
@Brechtpd After working on this PR, I finally figured out how your design works :) I do have the following suggestions regarding the pool token's mint/burn logic:
- Now we calculate the amount of tokens that will be accepted into the pool based on the Join's `poolAmountOut` parameter. If `poolAmountOut` is large enough, this join will likely to fail; otherwise, if it is small enough, the user ends up with a smaller amount of pool tokens than he deserves. I suggest we calculate the amount of pool tokens assuming his join will be accepted, then compare the new pool tokens to mint to him with a `minPoolTokenAmount` parameter that the user provides. If `minPoolTokenAmount` is smaller than or equal to the pool tokens to be minted, then this Join will be accepted, otherwise, the join will be …
> [AMM Pool] Rename variables and extract methods

- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeAdmins.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBalances.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeGenesis.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeTokens.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
Only for consistency. I did not measure any gas cost difference in any practical test, but in a completely isolated test case `public` used 40 gas less than `external`.
> [protocol 3.6] Changed lib functions from external to public

- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExchange.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitRequest.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinRequest.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
Tried to keep things as simple as possible (because locking/unlocking is normally not needed) and so didn't add yet another place balances could be stored.
Locking/unlocking should also be fairly simply, lock/unlock requests cannot overlap so that a state change between lock/unlock always takes `LOCK_DELAY` seconds. I think this makes things easy for the relayer.
> [AMM] Small improvements

- packages/loopring_v3.js/src/request_processors/deposit_processor.ts
- packages/loopring_v3.js/src/request_processors/withdrawal_processor.ts
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
- packages/loopring_v3/contracts/test/AmmPool.sol
Only renamed variables that don't impact any offchain processes (signatures, circuits). Not sure if this would be a problem at this point.
> [protocol 3.6] Rename owner to from/to for withdrawals/deposits

- packages/loopring_v3/contracts/amm/PoolToken.sol
- packages/loopring_v3/contracts/amm/libamm/AmmBlockReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmPoolToken.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUpdateProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
Changes how minting/burning works in #1816. This mints all liquidity tokens that will ever exist to the pool account on L2 so we can mint/burn doing simple transfers on L2. Liquidity tokens can still be burned onchain like usual where we need to.
I think this makes things cheaper/easier because the only thing we now use are transfers, deposits/withdrawals are never needed any more.
> [AMM] Mint/Burn directly on L2

- packages/loopring_v3/DESIGN.md
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/aux/agents/OpenGSN2Agent.sol
- packages/loopring_v3/contracts/core/iface/IExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/AccountUpdateTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/TransferTransaction.sol
- packages/loopring_v3/contracts/core/impl/libtransactions/WithdrawTransaction.sol
- packages/loopring_v3/test/testExchangeAccounts.ts
- packages/loopring_v3/test/testExchangeAgents.ts
- packages/loopring_v3/test/testExchangeDepositWithdraw.ts
- packages/loopring_v3/test/testExchangeInternalTransfer.ts
- packages/loopring_v3/test/testExchangeUtil.ts
- packages/loopring_v3/test/types.ts
#1847 
Also removed `approveOffchainTransfer` because we're not even using this ourselves, and easy to use libraries for this are now available.
> [protocol 3.6] Support max fee in all authorization methods

- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
- packages/loopring_v3/migrations/7_deploy_amm.js
- packages/loopring_v3/truffle.js
Just increases the `runs` parameter of the optimizer so it optimizes more for runtime efficiency than contract size. Saves ~1% gas on the operations I checked (deposits, AMM joins).
@kongliangzhong Is there a reason there is a `LoopringAmmPoolCopy`? Not possible to just call `LoopringAmmPool.new()` to create another copy?
> [protocol 3.6] Better optimizer settings

- packages/hebao_v1/contracts/base/BaseWallet.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/thirdparty/proxy/CloneFactory.sol
- packages/hebao_v1/test/testWalletCreation.ts
- Uses the optimized proxy code from https://eips.ethereum.org/EIPS/eip-1167. Like SimpleProxy it doesn't allow the wallet to be upgraded. Etherscan should also detect this as a proxy contract and should show the proxy interface, though I did not test this.
- Wallet `init` function now also can set modules directly instead of needing multiple calls on the wallet
When running the "anyone should be able to create a group of blank wallets" test which creates 10 wallets, with the 3 common modules initialized, the deployment cost is reduced from 3,649,674 gas to 2,103,030 gas, a 42% reduction. 35% of that 42% reduction is because of the much smaller deployment cost of the proxy contract.
This also reduces the cost of using the wallet because the implementation address is baked into the proxy …
> [hebao] Deploy optimizations

- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianUtils.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
- packages/hebao_v1/contracts/thirdparty/ens/ENSConsumer.sol
- packages/hebao_v1/deployment/deployer-goerli.js
- packages/hebao_v1/legacy/version1.0/contracts/security/SecurityModule.sol
- packages/hebao_v1/test/testERC1271Module.ts
- packages/hebao_v1/test/testLock.ts
- We remove the `onlyHaveEnoughGuardians` modifier so make sure `requireMajority` will check the number of active guardians is not empty.
- the first two guardians still don't have to wait a pending period
- If a function `doSomething` as a version that supports multi-sig authorization, I name it `doSomethingWA` where *WA* means *WithApproval*. I also make sure these two functions are next to each other. If a function only supports multisig, *WA* will be dropped from the function name
- Add default impl for `bindableMethods` in BaseModule
- Allow owner to lock his own wallet (regardless of the current lock status)
- Disable automatic unlock after 1 day. Do not track who locked the wallet.
- Lock and unlock does not check the previous status and will always succeed.
- Change the max number …
> [hebao 1.2] #2 lock permanently and unlock with approval

- packages/hebao_v1/contracts/modules/base/MetaTxAware.sol
- packages/hebao_v1/contracts/modules/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/FinalSecurityModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/transfers/FinalTransferModule.sol
- packages/hebao_v1/test/helpers/TestUtils.ts
At the request of GSN2 folks to reduce confusion.
> rename trustedForwarder to metaTxForwarder

- packages/loopring_v3.js/src/request_processors/withdrawal_processor.ts
- packages/loopring_v3/circuit/Circuits/WithdrawCircuit.h
- packages/loopring_v3/test/testExchangeUtil.ts
#1942
Before: 
- For forced withdrawals `storageID` needed to be valid for use with a nonce, but also required the value to be exactly the same as the one stored in the storage tree. This could be a problem (and the tests only picked the easy case by setting the value to `0` to make setting up the tests easier under these constraints).
After:
- Any `storageID` can be used for forced withdrawals, the value only matters for the witness, nothing else.
> [protocol36] Allow arbitrary storageID for forced withdrawals

- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
I'm back with batched call support. :)
Allow meta-txs or the wallet owner to do batched calls. I think also very important for efficiency (add multiple guardians, do multiple token transfers, whitelist multiple address,... or a combination of all of the above in multiple modules which isn't even possible with a module specific batch implementation)  with only the overhead of a single Ethereum tx/meta tx, which can be very significant (especially with reimbursement).
I think technically possible to support `txAwareHash` for batched calls, but I don't really see much use for that so kept things as simple as possible.
**Untested!**
> [hebao] batch call

- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianUtils.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
Locking a wallet should be a really urgent operation and shall not wait for any previous transactions to finish due to nonce dependency.
> [hebao] add `lockWA` that does not use nonce

- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/stores/QuotaStore.sol
- packages/hebao_v1/contracts/test/PriceCacheStore.sol
- packages/hebao_v1/contracts/thirdparty/SafeCast.sol
- packages/hebao_v1/migrations/9_modules.js
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
Reverted back to internal functions + caching `Quota`. A bit more functions and bloat, but caching `Quota` saves a nice 4,000 gas so seems worth it.
There's a ~3,000 gas overhead by having to call `currentQuota` to check if the quota is enabled, and so if the quota is enabled this is just extra cost. (in some cases `currentQuota` only needs to do 1 SLOAD in some cases when `pendingUntil` and either `currentQuota` or `pendingQuota` or stared in the same slot, but this would only work sometimes and I haven't found a clean way to do that yet).
But the if the quota is disabled there are of course savings, and this ends up being ~25,000 gas in the benchmark (~5,000 gas saved by being able to skip the whitelist check, ~5,000 gas saved by not having to get the token value from the price oracle, …
> [hebao] QuotaStore optimizations

- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/stores/QuotaStore.sol
- packages/hebao_v1/contracts/stores/SecurityStore.sol
- packages/hebao_v1/contracts/stores/WhitelistStore.sol
- packages/hebao_v1/contracts/test/PriceCacheStore.sol
- packages/hebao_v1/contracts/thirdparty/SafeCast.sol
- packages/hebao_v1/migrations/6_stores.js
- packages/hebao_v1/migrations/9_modules.js
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
Now a wallet's quota by default is 0, and it means the quota is unlimited, consuming quota will not update the quota value in QuotaStore to reduce gas. Values other than 0 will behave as usual.
@Brechtpd I'm not sure if `uint128(-1)` is the right way to calculate the max number for uint128.
> [hebao1.2] Allow unlimited quota

- packages/hebao_v1/contracts/base/Controller.sol
- packages/hebao_v1/contracts/modules/ControllerImpl.sol
- packages/hebao_v1/contracts/modules/aux/AddOfficialGuardianModule.sol
- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/base/MetaTxAware.sol
- packages/hebao_v1/contracts/modules/base/MetaTxModule.sol
- packages/hebao_v1/contracts/modules/core/ERC1271Module.sol
- packages/hebao_v1/contracts/modules/core/FinalCoreModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
- packages/hebao_v1/contracts/modules/security/FinalSecurityModule.sol
- packages/hebao_v1/contracts/modules/security/GuardianModule.sol
- packages/hebao_v1/contracts/modules/security/InheritanceModule.sol
- packages/hebao_v1/contracts/modules/security/SecurityModule.sol
- packages/hebao_v1/contracts/modules/security/WhitelistModule.sol
- packages/hebao_v1/contracts/modules/transfers/BaseTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/FinalTransferModule.sol
- packages/hebao_v1/contracts/modules/transfers/TransferModule.sol
- packages/hebao_v1/contracts/modules/upgrade/UpgraderModule.sol
- packages/hebao_v1/contracts/price/KyberNetworkPriceOracle.sol
- packages/hebao_v1/contracts/price/UniswapV2PriceOracle.sol
- packages/hebao_v1/contracts/test/PriceCacheStore.sol
- packages/hebao_v1/contracts/thirdparty/ens/BaseENSManager.sol
- packages/hebao_v1/contracts/thirdparty/ens/ENSConsumer.sol
- packages/hebao_v1/contracts/thirdparty/ens/ENSReverseRegistrarImpl.sol
- packages/hebao_v1/migrations/7_controller.js
- packages/hebao_v1/test/helpers/TestUtils.ts
- packages/hebao_v1/test/testQuotaTransfers.ts
So I found `immutable` exists since solidity 0.7 while reading the solidity github:
- https://solidity.readthedocs.io/en/v0.7.4/contracts.html?highlight=immutable#constant-and-immutable-state-variables
Allows immutable simple data to be initialized in the constructor without using storage, so as cheap to read as constants most times. So we could pass in constant values in the constructor with this without loss of efficiency (after we stopped doing that until recently...).
Maybe some other cases it could be used as well. 
Does it make sense to just simply cache the store addresses in `immutable` vars in modules? Doesn't seem likely we can just update the stores used in the modules without any upgrading. @dong77 
Same for `WalletFactory`, easy to replace the contract when needed so not that …
> [hebao 1.2] Start using immutable

- packages/hebao_v1/contracts/modules/base/BaseModule.sol
- packages/hebao_v1/contracts/modules/core/ForwarderModule.sol
- packages/hebao_v1/contracts/modules/core/WalletFactory.sol
#1995
We also can't allow just any call to `createWallet`, otherwise the wallet can be used to create other wallets successfully just with the signature of the owner without quota.
I think we could also just remove `skipQuota` all together because by default the quota isn't used now, and this also doesn't save that much gas because of that.
> [hebao 1.2] Fix skipQuota

- packages/loopring_v3/circuit/Circuits/AmmUpdateCircuit.h
- packages/loopring_v3/circuit/Circuits/UniversalCircuit.h
- packages/loopring_v3/circuit/Gadgets/AccountGadgets.h
- packages/loopring_v3/circuit/Gadgets/MathGadgets.h
- packages/loopring_v3/circuit/main.cpp
- packages/loopring_v3/circuit/test/MathTests.cpp
Fixed some issues/bugs found while running trusted setup scripts which does some additional checks.
These changes fix the "unconstrained variables" warnings (which isn't always a bug, sometimes just variables that aren't actually used).
Trusted setup scripts still don't work unfortunately because the proving key format was changed after the prover optimizations and my updated code to import the bellman proving key doesn't work yet. Working on that now.
> [protocol 3.6] Circuit fixes

- packages/loopring_v3/contracts/core/impl/libtransactions/DepositTransaction.sol
There is small issue with the current code, if a user did two 0-deposits, after we process the first one,the second one is gone onchain so the processing of the second one will fail.
> [Protocol 3] Allow better processing of 0 deposits

- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/test/testAMMPool.ts
- packages/loopring_v3/test/testExchangeAMM.ts
`amount` is an uit96, and for big amounts `amount * 100000` is of course bigger than `uint96`, but solidity keeps precision in uint96.
> [AMM] Fix overflow in isAlmostEqual checks

- packages/loopring_v3/contracts/amm/libamm/AmmBlockReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUpdateProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/aux/access/LoopringIOExchangeOwner.sol
- packages/loopring_v3/contracts/aux/agents/AgentRegistry.sol
- packages/loopring_v3/contracts/core/iface/ExchangeData.sol
- packages/loopring_v3/contracts/core/iface/IAgentRegistry.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeBlocks.sol
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testExchangeBlocks.ts
- packages/loopring_v3/test/testExchangeUtil.ts
Only change for the relayer is that the AMM transactions verified in the pool contracts need to have `approved = true` in `AuxiliaryData`, and otherwise `approved = false`. `bool  approved` is a new field in `AuxiliaryData`.
This seems to save around 25% of the gas cost of a join/exit.
> [protocol3.6] AMM pool txs optimization

- packages/loopring_v3.js/src/compression.ts
- packages/loopring_v3/contracts/test/LzDecompressorContract.sol
- packages/loopring_v3/contracts/test/ZeroDecompressorContract.sol
- packages/loopring_v3/test/testCompression.ts
- packages/loopring_v3/test/testDebugTools.ts
I saw that we don't make use yet of data compression on mainnet. I did some tests on actual blocks submitted on mainnet to find good parameters for realistic data.
I also used Tenderly on a few blocks to simulate how much gas would have been spend if compression would have been used. I found that ~50k gas is saved per block. Pretty nice for something that doesn't need much work for the relayer to implement (just call `compressZeros` on the block data and set `isDataCompressed` to true when calling `submitBlocksWithCallbacks`).
This doesn't need any additional contract changes, the currently deployed contracts already support this.
> [protocol 3.6] Compression benchmarks

- packages/loopring_v3/circuit/Circuits/AccountUpdateCircuit.h
- packages/loopring_v3/circuit/Circuits/AmmUpdateCircuit.h
- packages/loopring_v3/circuit/Circuits/SignatureVerificationCircuit.h
- packages/loopring_v3/circuit/Circuits/TransferCircuit.h
- packages/loopring_v3/circuit/Circuits/UniversalCircuit.h
- packages/loopring_v3/circuit/Circuits/WithdrawCircuit.h
- packages/loopring_v3/circuit/Gadgets/MatchingGadgets.h
- packages/loopring_v3/circuit/Gadgets/MathGadgets.h
- packages/loopring_v3/circuit/Gadgets/MerkleTree.h
- packages/loopring_v3/circuit/Gadgets/OrderGadgets.h
- packages/loopring_v3/circuit/Gadgets/SignatureGadgets.h
- packages/loopring_v3/circuit/Gadgets/StorageGadgets.h
- packages/loopring_v3/circuit/test/OrderTests.cpp
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/util/find_optimal_poseidon.py
We have learned that the theoretical security of ~100 bits is actually higher in practice due to the nature of that there is an TNFS attack. However, the bottleneck for attacks like that are is not computation but memory shuffles, so measuring the complexity in just arithmetic operations isn't accurate. A number of papers have tried to approach the theoretical security parameter using custom hardware to these memory shuffles, but still haven not achieved the theoretical parameter. So the practical is several bits higher than the reported parameter, even when using custom hardware.
Practically it's also just a major change that really changes the basics of what we build upon (also for doing things like the trusted setup). The  EIP which will bring BLS12-381 support has also been removed …
> [protocol 3.6] Audit feedback

- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
This PR is to make sure we disable onchainTransferFrom for now.
> [protocol3.6] improve security on onchainTransferFrom method

- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitRequest.sol
- packages/loopring_v3/contracts/amm/libamm/AmmTransactionReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUpdateProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmUtil.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawal.sol
- packages/loopring_v3/contracts/aux/agents/FastWithdrawalAgent.sol
- packages/loopring_v3/contracts/aux/bridge/Bridge.sol
- packages/loopring_v3/contracts/aux/fast-withdrawal/FastWithdrawalLiquidityProvider.sol
- packages/loopring_v3/contracts/converters/BaseConverter.sol
- packages/loopring_v3/contracts/core/impl/ExchangeV3.sol
- packages/loopring_v3/contracts/lib/Drainable.sol
- packages/loopring_v3/contracts/lib/LPERC20.sol
- packages/loopring_v3/contracts/lib/TransferUtil.sol
> Converter/Bridge Feedback

- packages/loopring_v3.js/src/constants.ts
- packages/loopring_v3.js/src/request_processors/spot_trade_processor.ts
- packages/loopring_v3/circuit/Circuits/SpotTradeCircuit.h
- packages/loopring_v3/circuit/Gadgets/MathGadgets.h
- packages/loopring_v3/circuit/Gadgets/OrderGadgets.h
- packages/loopring_v3/circuit/Gadgets/SignatureGadgets.h
- packages/loopring_v3/circuit/Utils/Constants.h
- packages/loopring_v3/circuit/test/OrderTests.cpp
- packages/loopring_v3/test/testExchangeRingSettlement.ts
- packages/loopring_v3/test/testExchangeUtil.ts
#2334 
Currently I have set the multiplier to `50`, so now it's also possible to set the fee up to 31.5% in steps of 0.5%. But is easy to change if some other value would make more sense.
All inputs to the circuit remains, it's just that `feeBips` values `> 0.63%` will automatically enable the new mode so the passed in `feeBips` values need to be multiples of `0.5%`.
> [protocol 3] Addded option for increased trading fees

- packages/loopring_v3/contracts/aux/bridge/Bridge.sol
- packages/loopring_v3/contracts/aux/bridge/IBridge.sol
- packages/loopring_v3/test/testBridge.ts
#2345
One last name question: in `IBridgeConnector.processProcessorTransactions()` where does the `Processor` come from? Why not just `IBridgeConnector.processTransactions()`?
> [Protocol 3.7] Fix typos + add benchmark test

- packages/loopring_v3/contracts/amm/AmplifiedAmmController.sol
- packages/loopring_v3/contracts/amm/IAmmController.sol
- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmDepositProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmSignature.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmTransactionReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawProcess.sol
- packages/loopring_v3/migrations/7_deploy_amm.js
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testAMMPool.ts
> The flexibility to use SET_VIRTUAL_BALANCE on L2 to change the virtual balances after pools are initialized, so we can re-use the same pool contract and the LP token. We can use a time lock to prevent ourselves from being evil.
Changed the interface to allow updating the virtual balances more easily. Also implemented a very simple mechanism in `AmplifiedAmmController.sol` but could easily be updated to support other methods if we need it.
> The relayer can decide to use the virtual balances as-is, or use smaller values (while keeping the ratio/price) that are >= actual balances. With this approach, any pool with a >1 initial AF will fall back to the full spectrum of the curve. In otherwords, the virtual balances are the maximum virtual balances. we can use any values between the actual …
> Amm v2 - More flexible virtual balances

- packages/loopring_v3/contracts/amm/AmplifiedAmmController.sol
- packages/loopring_v3/contracts/amm/IAmmController.sol
- packages/loopring_v3/contracts/amm/LoopringAmmPool.sol
- packages/loopring_v3/contracts/amm/libamm/AmmData.sol
- packages/loopring_v3/contracts/amm/libamm/AmmDepositProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmExitProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmJoinProcess.sol
- packages/loopring_v3/contracts/amm/libamm/AmmPoolToken.sol
- packages/loopring_v3/contracts/amm/libamm/AmmSignature.sol
- packages/loopring_v3/contracts/amm/libamm/AmmStatus.sol
- packages/loopring_v3/contracts/amm/libamm/AmmTransactionReceiver.sol
- packages/loopring_v3/contracts/amm/libamm/AmmWithdrawProcess.sol
- packages/loopring_v3/migrations/7_deploy_amm.js
- packages/loopring_v3/test/ammUtils.ts
- packages/loopring_v3/test/testAMMPool.ts
#2449
Allows the controller to enter exit mode, which allows the operator to exit users from the pool if no fee needs to be paid.
Also allows the controller to re-use the pool with different tokens when the supply is `0`.
I used the controller as the authorized address because pools currently don't have an owner and exit mode/pool re-using a pool even with no supply may not work for all types of pools.
Made `permit` public to make the Pool contract smaller because the contract size was too large.
> Amm v2 - Exit mode and pool reuse

- packages/hebao_v2/contracts/base/SmartWallet.sol
- packages/hebao_v2/contracts/base/libwallet/GuardianLib.sol
- packages/hebao_v2/contracts/base/libwallet/RecoverLib.sol
- packages/hebao_v2/contracts/base/libwallet/WalletData.sol
- packages/hebao_v2/contracts/test/LRCToken.sol
- packages/hebao_v2/contracts/thirdparty/MockContract.sol
- packages/hebao_v2/contracts/thirdparty/strings.sol
需要为setInitialGuardians和recover增加测试或者修改测试
@kongliangzhong
> Hebao v2: fix potential duplicate guardian bug

- packages/loopring_v3/contracts/aux/access/LoopringIOExchangeOwner.sol
Just noticed that we removed the universal-agent checks in the LoopringIOExchangeOwner contract.
From my understanding, these checks are necessary. So I add it back.
I'd checked the contract we are using on mainnet, the universal-agent checks are there.
> [protocols3.6]callback recievers must be a universal agent

- packages/counterfactual_nft/README.md
- packages/counterfactual_nft/contracts/AddressSet.sol
- packages/counterfactual_nft/contracts/CounterfactualNFT.sol
- packages/counterfactual_nft/contracts/ICounterfactualNFT.sol
- packages/counterfactual_nft/contracts/Migrations.sol
- packages/counterfactual_nft/contracts/NFTFactory.sol
- packages/counterfactual_nft/contracts/external/CloneFactory.sol
- packages/counterfactual_nft/contracts/external/IL2MintableNFT.sol
- packages/counterfactual_nft/contracts/external/IPFS.sol
- packages/counterfactual_nft/contracts/external/OwnableUpgradeable.sol
- packages/counterfactual_nft/deploy.sh
- packages/counterfactual_nft/flatten.sh
- packages/counterfactual_nft/migrations/1_initial_migrations.js
- packages/counterfactual_nft/migrations/2_deploy_contracts.js
- packages/counterfactual_nft/package.json
- packages/counterfactual_nft/test/test.js
- packages/counterfactual_nft/truffle.js
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeNFT.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeWithdrawals.sol
- packages/loopring_v3/contracts/test/nft/CloneFactory.sol
- packages/loopring_v3/contracts/test/nft/CounterfactualNFT.sol
- packages/loopring_v3/contracts/test/nft/ICounterfactualNFT.sol
- packages/loopring_v3/contracts/test/nft/NFTFactory.sol
- packages/loopring_v3/test/testExchangeNFT.ts
Adds the counterfactual NFT contracts in this repo.
These contracts get their own subfolder because they are independent but I also made simplified test versions directly in the protocol subfolder for ease of testing (and to minimize version clashing because the `pragma` mode doesn't seem supported with our currently used packages in the protocols subfolder).
> Counterfactual NFTs

- packages/loopring_v3/contracts/core/impl/DefaultDepositContract.sol
- packages/loopring_v3/contracts/core/impl/libexchange/ExchangeDeposits.sol
ETH not returned to deposit account when msg.value > 0 and deposit amount == 0.
> [loopringv3] improve ETH deposit handling logics in DepositContract

- packages/counterfactual_nft/contracts/CounterfactualNFT.sol
- packages/counterfactual_nft/contracts/CounterfactualNftExt.sol
- packages/counterfactual_nft/contracts/WithCreator.sol
Changes:
1. disable minting on L1
2. add creator info for token id (in order to keep compatible with opensea)
> [counterfactual_nft] Disable minting on L1 and add creator

- packages/counterfactual_nft/contracts/CounterfactualNftExt.sol
- packages/counterfactual_nft/flatten.sh
- packages/counterfactual_nft/flattened/CounterfactualNftExt_flat.sol
- packages/counterfactual_nft/flattened/NFTFactory_flat.sol
When the last value in the constructor is encoded to all zeros, it will trigger a bug when doing code verification in etherscan.
So I changed the order of params.
> [counterfactual_nft] Minor change to avoid a code verification bug in etherscan
